[package]
name = "vscode-update"
version = "0.1.0"
authors = ["hbobenicio <hbobenicio@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
log = "0.4"
env_logger = "0.8.2"
reqwest = { version = "0.10.10", features = ["blocking"] }
